### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by abh** [cathalgarvey/fmtless#1]
It's pretty weird that you take BSD licensed code, modify it a little and then re-license it under a much more restrictive license.

**Comment by cathalgarvey** [comment]
It's pretty weird that you care, when the BSD is explicitly designed to let me do pretty much whatever I please.

If the authors wanted to guarantee the future liberty of the code maybe the should have used another license...oh! Wow, we've come full circle. :)

Also, if you had read the code before complaining, you'd have found there's plenty of original shim code in here. That's what's being licensed, obviously. Take it or leave it.

Have a great day!

Closes #1

On 29 August 2016 04:56:03 GMT+01:00, "Ask Bjørn Hansen" <notifications@github.com> wrote:
>It's pretty weird that you take BSD licensed code, modify it a little
>and then re-license it under a much more restrictive license.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cathalgarvey/fmtless/issues/1

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by abh** [comment]
Same to you! :-) I didn't mean to offend, I was just surprised about the unusual choice of license for this particular "eco system".

**Comment by cathalgarvey** [comment]
Sorry to be crabby; I recognise that you share the same values as I do, in particular the continued liberty of code. We simply choose different ways to ensure that liberty; I use licensing, you use social pressure.

That's great, but I wish people would use that social pressure on companies that tivoise and proprietarise open source, instead of pressuring people who are developing new Free / Open code to use their preferred license.
